---
abstract: 'L<Padre> and XML'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  File::Slurp: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3614'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Padre-Plugin-XML
provides:
  Padre::Plugin::XML:
    file: lib/Padre/Plugin/XML.pm
    version: 0.10
  Padre::Plugin::XML::Document:
    file: lib/Padre/Plugin/XML/Document.pm
    version: 0.10
  Padre::Task::SyntaxChecker::XML:
    file: lib/Padre/Task/SyntaxChecker/XML.pm
    version: 0.10
requires:
  Padre: 0.65
  XML::LibXML: 1.67
  XML::Tidy: 1
resources:
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-XML/
version: 0.10
